version: "3.8"

services:
  site:
    image: igortrindade13/site:latest
    environment:
      DB_HOST: 34.193.31.124  # coloque o endereço do banco externo
      DB_USER: backend
      DB_PASSWORD: synkro
      DB_NAME: synkro
      DB_PORT: 3306
    ports:
      - "80:80"
    networks:
      - synkro-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure


networks:
  synkro-net:
    driver: overlay
